Repository deepak00011/Hacktoberfest, pull requests merged in 2023-10, with the labels that each got.

#20 Create gamestonepaper.py
  python/gamestonepaper.py
Labels: hacktoberfest accepted

#18 Create twosum.c
  c/twosum.c
Labels: hacktoberfest accepted

#17 Create sparse_matrix.c
  sparse_matrix.c
Labels: hacktoberfest accepted

#21 created python scraper
  README.md
  python/getGoogleresult.py
Labels: hacktoberfest, hacktoberfest 2023, hacktoberfest accepted

#22 Create getdata.py
  Flask/getdata.py
Labels: good first issue, hacktoberfest, hacktoberfest 2023, hacktoberfest accepted

#24 Create newsAPi.py
  happy-hacking/newsAPi.py
Labels: good first issue, hacktoberfest, hacktoberfest 2023, hacktoberfest accepted

#26 Create newFlaskFestAPi.py
  Flask/newFlaskFestAPi.py
Labels: good first issue, hacktoberfest, hacktoberfest 2023, hacktoberfest accepted, hacktoberfest - accepted

#27 Create getresult.js
  node/getresult.js
Labels: good first issue, hacktoberfest, hacktoberfest 2023, hacktoberfest accepted, hacktoberfest - accepted

#28 Create GoogleSearchController.java
  java/getdata/GoogleSearchController.java
Labels: good first issue, hacktoberfest, hacktoberfest 2023, hacktoberfest accepted, hacktoberfest - accepted

#30 Create NewsController.java
  java/newsAPI/NewsController.java
Labels: hacktoberfest, hacktoberfest 2023, hacktoberfest accepted, hacktoberfest - accepted

#29 Create GoogleSearchApplication.java
  java/getdata/GoogleSearchApplication.java
Labels: good first issue, hacktoberfest, hacktoberfest 2023, hacktoberfest accepted, hacktoberfest - accepted
